[[headers]]
for = "/examples/assets/*"
[headers.values]
Access-Control-Allow-Origin = "*"
[[headers]]
for = "/examples/assets/*.pngbin"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "image/jpeg"